spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cybersport}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

jwt:
  subject: user
  issuer: cybersport
  secret: J7gzxczxcQgfJ7gQgfczxc
  tokenExpiresIn: 432000
