spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://185.209.160.32:5432/cybersport}
    username: ${SPRING_DATASOURCE_USERNAME:vl7sha}
    password: ${SPRING_DATASOURCE_PASSWORD:kITypNEYMenT}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

jwt:
  subject: user
  issuer: cybersport
  secret: J7gzxczxcQgfJ7gQgfczxc
  tokenExpiresIn: 432000

admin:
  email: "admin@admin.ru"
  password: "1234"

urls:
  frontend:
    base: "http://localhost:4200"
    registration-page: "http://localhost:4200/registration"
    join-team-page: "http://localhost:4200/teams/join"

invites:
  expires-in-days: 2

mail:
  host: smtp.mail.ru
  port: 465
  username: "vl7shabyandex.ru@mail.ru"
  password: xMdQjsywQjvNHLSDYJih
  protocol: smtps
  smtps.auth: true