spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://185.209.160.32:5432/cybersport}
    username: ${SPRING_DATASOURCE_USERNAME:vl7sha}
    password: ${SPRING_DATASOURCE_PASSWORD:kITypNEYMenT}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

jwt:
  subject: user
  issuer: cybersport
  secret: J7gzxczxcQgfJ7gQgfczxc
  tokenExpiresIn: 432000

admin:
  email: "admin@admin.ru"
  password: "1234"
  name: "admin"
  surname: "admin"
  secondName: "admin"
  contact: "admin@admin.ru"
  datOfBirth: 
  theSubjectOfTheRF: "Samara"
  city: "Samara"

urls:
  frontend:
    registration-page: "http://localhost:4200/registration"